draganddrop: draganddrop.c
	gcc -o draganddrop draganddrop.c `sdl2-config --cflags --libs`	
draganddrop.o: draganddrop.c
	gcc -o draganddrop draganddrop.c `sdl2-config --cflags --libs`	
test:
	gcc -o test test.c
clean:
	rm -f draganddrop.exe
	rm -f test.exe
