CC=gcc
FLAGS=-lfreeglut -lopengl32 -lglu32 -lm

all: opengl01.exe opengl02.exe opengl03.exe opengl04.exe opengl05.exe opengl06.exe opengl07.exe opengl08.exe opengl09.exe opengl10.exe

opengl01.exe: opengl01.c
	$(CC) opengl01.c $(FLAGS) -o opengl01
opengl02.exe: opengl02.c
	$(CC) opengl02.c $(FLAGS) -o opengl02
opengl03.exe: opengl03.c
	$(CC) opengl03.c $(FLAGS) -o opengl03
opengl04.exe: opengl04.c
	$(CC) opengl04.c $(FLAGS) -o opengl04
opengl05.exe: opengl05.c
	$(CC) opengl05.c $(FLAGS) -o opengl05
opengl06.exe: opengl06.c
	$(CC) opengl06.c $(FLAGS) -o opengl06
opengl07.exe: opengl07.c
	$(CC) opengl07.c $(FLAGS) -o opengl07
opengl08.exe: opengl08.c
	$(CC) opengl08.c $(FLAGS) -o opengl08
opengl09.exe: opengl09.c
	$(CC) opengl09.c $(FLAGS) -o opengl09
opengl10.exe: opengl10.c
	$(CC) opengl10.c $(FLAGS) -o opengl10

clean:
	rm opengl01.exe opengl02.exe opengl03.exe opengl04.exe opengl05.exe opengl06.exe opengl07.exe opengl08.exe opengl09.exe opengl10.exe
